sudo: required

language: python

cache: pip

node_js:
  - "10"

cache:
  directories:
  - $HOME/.local

python:
  - "2.7"

services:
  - docker

before_install:
  - pip install awscli

script:
  # - docker build . -t 428728527901.dkr.ecr.eu-west-1.amazonaws.com/vue-demo
  - eval $(aws ecr get-login --region eu-west-1)
  - docker push 428728527901.dkr.ecr.eu-west-1.amazonaws.com/vue-demo
env:
  global:
    - secure: yVWDU5n7sfc05m7eBDzT7Jo16MuzwwIicv8WIsChHftI2+cotj5HIAjNEgGiPM3E+B7KGaRLbFJzipH8zAck1ZVUUYeOf5HE8s9velftKU3i2exCwqBlFiPFbDGqUEJvrvDu6FUShTa+JRGW6uZeOUqbQRKOKF/WcFw99RPxltx8gkNLMI9xGiDPDSN0EA9K36aWioRyoxfh1vE12aGD10wuddD6FAQYEjABPUYcJNQ0kK2OcnnkV36nW+usnrlWo1ECeqx4NPMeiwGQnZ4qzvAtXaG0kr7WHGmahHZLfKL3FB1+4Ng7/p2xPDab4BvFekEw3NmmAq5lmzBPrwh3Ql2OHKcBVovZld7nVY9pMovkImoyoh8r3eDkV3YxYwXJCDpNL2ljbCreraPl9ZICO9sSHqcR57INLIlKRQzshn7FNX53TPZ/RefQLVl4LWC2ygZWnxDuH90xRf2tp5sOXVb5fRgQqCRGNf0QOkobmURYkBmBNlKXzIODnGYYObPESDtUMSKFxb67I4bkSeqaHqWN7ZNIXnXpOm8GoG+Jx/SwEEfovJlmtc7i01KIXy++ksZ/2XECnVHG7Izs8ePxf1eiH4cA6qEyclNxVFHdqEyfIORy3Eze9xBgohBFY8Kej2UaWxikSnmC++TN7mPqiY/KoXehd7ucBdCCFjkQ5PQ=
    - secure: 1kQ8+KsgnxisBZ8hffaiLh2RNrr6i98lTPSkc8WiwIP66CoSzLXncnc4Dsbjj+pczhX8p4mlDc5DHU8P7NBbFlrceN/EePYgb7wTqYTbeqnlMxOoHcZtwSZd0twx9b49WOnk7YfOXOzYupoNrnNHxTrjhoj4zFZw3RU/VGzopKKl9Sd+bgGNPqraQGKBPwIaVTeNXcz4UDs+JPLvwAXn7GvrE1Wyf5BGMa/nGyuVs1nAkTlFWuZbUjg3aP3CxoFELM6hQT6nyLiLDj7huLjbwexXZSLV+9PPTtPzcTh40ZOyBlrFPoIc2LQwc9CW00eHmwWV/Pti8UsafODULqWdlR9cn7wWUmLwlrAdP/NdVxf9H+3JbIFDpMBNkkjom0m4UnOJhMzAtSHVELYaddMIcKHrZ6WaXHykbP2cuY3hwrK8XCcNwvhwhOgxsBn/LsVLR/KA0DKuQV+7o1StKnezyAlvch8LKLtjW2oGjMAl+HwpW+DqwYAghbKRtmKRkvV1QGbK0fj80nxs/pnKJvsQwK+KtZrwBM3dAEazCzVKNPDEqoT+p9pfab9PFDg26weZwju9Cgi4UdUArWyExe77IqsoViOdZetzHEijdlev8uwsxszwqL8ugRTmVIkH7te34RwfQWXJI6u5KcpT+0jo8SPSwDoYDO/XvJBH+FL53Vc=
